List<Map<String, dynamic>> characters = [
  {
    'name': 'mario',
    'img': 'assets/characters/mario.jpg',
    'desc': 'base character',
    'cost': 0,
    'unlocked': true,
  },
  {
    'name': 'duck',
    'img': 'assets/characters/duck.jpg',
    'desc': 'a common character',
    'cost': 10000,
    'unlocked': false,
  },
  {
    'name': 'boo',
    'img': 'assets/characters/boo.jpg',
    'desc': 'play as boo',
    'cost': 20000,
    'unlocked': false,
  },
  {
    'name': 'goomba',
    'img': 'assets/characters/goomba.jpg',
    'desc': 'a common character',
    'cost': 8000,
    'unlocked': false,
  },
  {
    'name': 'luigi',
    'img': 'assets/characters/luigi.jpg',
    'desc': 'mario\'s brother',
    'cost': 30000,
    'unlocked': false,
  },
  {
    'name': 'princess',
    'img': 'assets/characters/princess.jpg',
    'desc': 'the center of mario universe',
    'cost': 50000,
    'unlocked': false,
  },
  {
    'name': 'shroom',
    'img': 'assets/characters/shroom.jpg',
    'desc': 'power up character',
    'cost': 12000,
    'unlocked': false,
  },
  {
    'name': 'star',
    'img': 'assets/characters/star.jpg',
    'desc': 'power up character',
    'cost': 18000,
    'unlocked': false,
  },
  {
    'name': 'sunny',
    'img': 'assets/characters/sunny.jpg',
    'desc': 'power up character',
    'cost': 15000,
    'unlocked': false,
  },
];
